// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vSW0qH3tOgJ-qazF4ROIZg1gVgqllJk',
    appId: '1:473484473329:web:f407da95f122e7b4b98a50',
    messagingSenderId: '473484473329',
    projectId: 'flutterwebnoti',
    authDomain: 'flutterwebnoti.firebaseapp.com',
    storageBucket: 'flutterwebnoti.appspot.com',
    measurementId: 'G-7VL5PB78HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASAyll7d-0eDk3jESku0iYwt8sz2eEbFw',
    appId: '1:473484473329:android:20d603f4e3e1edafb98a50',
    messagingSenderId: '473484473329',
    projectId: 'flutterwebnoti',
    storageBucket: 'flutterwebnoti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV6cln45r68eNkKoOQ_TuwRpDElpdicQo',
    appId: '1:473484473329:ios:5e8f1a88a1819a36b98a50',
    messagingSenderId: '473484473329',
    projectId: 'flutterwebnoti',
    storageBucket: 'flutterwebnoti.appspot.com',
    iosBundleId: 'com.example.flutterWebNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV6cln45r68eNkKoOQ_TuwRpDElpdicQo',
    appId: '1:473484473329:ios:5e8f1a88a1819a36b98a50',
    messagingSenderId: '473484473329',
    projectId: 'flutterwebnoti',
    storageBucket: 'flutterwebnoti.appspot.com',
    iosBundleId: 'com.example.flutterWebNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2vSW0qH3tOgJ-qazF4ROIZg1gVgqllJk',
    appId: '1:473484473329:web:e7379dcca0646ad8b98a50',
    messagingSenderId: '473484473329',
    projectId: 'flutterwebnoti',
    authDomain: 'flutterwebnoti.firebaseapp.com',
    storageBucket: 'flutterwebnoti.appspot.com',
    measurementId: 'G-CC7EPD7TF1',
  );
}
